site_name: Projeto Hedy Lamarr
site_url: https://fcte-qualidade-de-software-1.github.io/2025-2_T01_HEDDY-LAMAR/
docs_dir: docs
repo_url: https://github.com/FCTE-Qualidade-de-Software-1/2025-2_T01_HEDDY-LAMAR
repo_name: FCTE-Qualidade-de-Software-1/2025-2_T01_HEDDY-LAMAR

theme:
  name: material
  logo: assets/logo-unb.png
  favicon: assets/favicon.png
  palette:
    - scheme: default
      primary: red
      accent: red
    - scheme: slate
      primary: black
      accent: red
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.copy
    - content.code.annotate
    - navigation.tabs.sticky

nav:
  - Home: index.md
  - Fase 1 - Propósito da Avaliação:
    - "Fase 01 - Requisitos de Avaliação": fase_1/index.md
  - Fase 2 - Especificação da Avaliação:
    - "Aplicação GQM": fase_2/index.md
    - "1° Objetivo de Medição: Adequação Funcional": fase_2/obj_adequacao_funcional.md
    - "2° Objetivo de Medição: Portabilidade": fase_2/obj_portabilidade.md
  - Fase 3 - Plano da Avaliação:
    - "Fase 03 - Plano de Execução da Avaliação": fase_3/index.md
  - Fase 4 - Execução da Avaliação:
    - "Fase 4 - Execução da Avaliação": fase_4/index.md

plugins:
  - minify

markdown_extensions:
  - footnotes
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
